In [1]:
import numpy as np

# Creation of a Matrix

In [2]:
matrix_1 = np.array([[2, 4], [5, 6]])
print(matrix_1)

[[2 4]
 [5 6]]


In [3]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(matrix_2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [6]:
matrix_2.shape

(3, 3)

In [7]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.26348517 0.07256219 0.33831528]
 [0.78721793 0.38643834 0.85563199]
 [0.99316943 0.3585889  0.71889772]]


In [9]:
random_integer_matrix = np.random.randint(1, 100, size = (4, 5))
print(random_integer_matrix)

[[26 22 84 49 10]
 [ 6 33 83 31 30]
 [92  2 17 12  3]
 [14 37 65 94 13]]


In [13]:
matrix_3 = np.ones((2, 3), dtype = 'int')
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [16]:
null_matrix = np.zeros((2, 3), dtype = 'int')
print(null_matrix)

[[0 0 0]
 [0 0 0]]


In [20]:
identity_matrix = np.eye(3, 3, dtype = 'int')
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# Transpose of a Matrix

In [22]:
a = np.random.randint(1, 100, size = (5, 6))
print(a)

[[86 75 34 47 15 83]
 [92 27 56 18 87 40]
 [41 38 77 39 75 40]
 [79 12 81 86 95 67]
 [89 53 44 41 72 42]]


In [23]:
transpose_matrix = np.transpose(a)
print(transpose_matrix)

[[86 92 41 79 89]
 [75 27 38 12 53]
 [34 56 77 81 44]
 [47 18 39 86 41]
 [15 87 75 95 72]
 [83 40 40 67 42]]


# Matrix Addition

In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [29]:
print(A)

[[1 2]
 [3 4]]


In [27]:
print(B)

[[5 6]
 [7 8]]


In [34]:
A.shape

(2, 2)

In [35]:
B.shape

(2, 2)

In [36]:
sum = A + B
print(sum)

[[ 6  8]
 [10 12]]


In [37]:
matrix_1 = np.random.randint(1, 100, size = (3, 3))
matrix_2 = np.random.randint(1, 50, size = (3, 3))

In [38]:
print(matrix_1)

[[27  9 91]
 [71 76 97]
 [56 51 99]]


In [39]:
print(matrix_2)

[[24 98 53]
 [39 31 66]
 [41 45 31]]


In [40]:
sum = np.add(matrix_1, matrix_2)
print(sum)

[[ 51 107 144]
 [110 107 163]
 [ 97  96 130]]


# Matrix Subtraction

In [43]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [45]:
print(A)

[[1 2]
 [3 4]]


In [46]:
print(B)

[[5 6]
 [7 8]]


In [41]:
difference = A - B
print(difference)

[[-4 -4]
 [-4 -4]]


In [48]:
matrix_1 = np.random.randint(1, 100, size = (3, 3))
matrix_2 = np.random.randint(1, 50, size = (3, 3))

In [49]:
print(matrix_1)

[[58 98 46]
 [23  5 36]
 [80 73 59]]


In [50]:
print(matrix_2)

[[49 48 38]
 [ 4 27 28]
 [11 40 25]]


In [51]:
diff = np.subtract(matrix_1, matrix_2)
print(diff)

[[  9  50   8]
 [ 19 -22   8]
 [ 69  33  34]]


# Multiplying a Matrix by a Scalar

In [52]:
x = 5
y = np.random.randint(1, 20, size = (4, 4))

In [53]:
print(y)

[[17 14 13  1]
 [ 2 16  7  7]
 [ 9 15  3 12]
 [12  1  1 17]]


In [55]:
product = np.multiply(x, y)
print(product)

[[85 70 65  5]
 [10 80 35 35]
 [45 75 15 60]
 [60  5  5 85]]


# Multiplication of 2 Matrices

In [56]:
matrix_3 = np.random.randint(1, 5, size = (3, 3))
matrix_4 = np.random.randint(1, 5, size = (3, 4))

In [57]:
print(matrix_3)

[[3 1 4]
 [2 1 3]
 [1 2 3]]


In [58]:
print(matrix_4)

[[3 1 1 1]
 [2 3 2 4]
 [3 4 4 4]]


In [60]:
product = np.dot(matrix_3, matrix_4)
print(product)

[[23 22 21 23]
 [17 17 16 18]
 [16 19 17 21]]


In [61]:
product.shape

(3, 4)