# Creating Numpy Arrays

In [4]:
import numpy as np

In [1]:
arr1 = np.array([1,2,3,4,5]) # 1D Array
arr2 = np.array([[1,2,3,4],[5,6,7,8]]) # 2D Array
arr3 = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]]) # 3D Array

print(arr1)
print(arr2)
print(arr3)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


# Creating Arrays from Scratch

In [2]:
print(np.zeros((3,3))) # 3x3 matrix or array of zeros
print(np.ones((2,4))) # 2x4 matrix of ones
print(np.full((4,4),7)) # 4x4 matrix which contains only number 7
print(np.eye(3)) # 3x3 identity matrix.
print(np.linspace(0,1,5)) # Evenly spaced array from number 0 to 1. 
print(np.arange(1,10,2)) # An array from number 1 to 9 incrementing by 2.

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.   0.25 0.5  0.75 1.  ]
[1 3 5 7 9]


# Checking Array Properties

In [3]:
arr4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Shape:", arr4.shape) # Shape
print("Dimension:", arr4.ndim) # Dimension
print("Size:", arr4.size) # Size
print("Data Type:", arr4.dtype) # Data Type

Shape: (2, 4)
Dimension: 2
Size: 8
Data Type: int32


# Changing Data Types

In [35]:
arr5 = np.array([1, 2, 3, 4], dtype = 'float32') # Explicit conversion
print(arr5)

arr6 = arr5.astype(np.int32) # Converting float to int
print(arr6)

[1. 2. 3. 4.]
[1 2 3 4]


# Reshaping and Flattening Arrays

In [38]:
arr7 = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(arr7.shape) # Checking the shape of the array

reshaped_array = arr7.reshape((4,2)) # Reshaping of an array
print(reshaped_array)

flattened_array = arr7.flatten() # Converting 2D array to 1D array
print(flattened_array)

(2, 4)
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
[10 20 30 40 50 60 70 80]
