# Looping Over Arrays in Python

In [9]:
import numpy as np
arr1=np.array([1,2,3,4])
result=[]

# Using a loop to square each element (slow)
for num in arr1:
    result.append(num**2)
print(result)

[1, 4, 9, 16]


 # Vectorization: Fixing the Loop Problem

In [5]:
arr2=np.array([1,2,3,4])
arr3=arr2**2 #Vectorized Operation
print(arr3)

[ 1  4  9 16]


# Broadcasting: Scaling Arrays Without Extra Memory

In [7]:
arr4=np.array([1,2,3,4,5])
arr5=arr4 + 10 # Broadcasting: 10 is added to all elements
print(arr5)

[11 12 13 14 15]


# Broadcasting with Arrays of Different Shapes

In [12]:
# Broadcasting with Two Arrays
arr6=np.array([1,2,3,4,5])
arr7=np.array([6,7,8,9,10])
print(arr6+arr7) # Element-wise addition

# Broadcasting a 2D Array and a 1D Array
arr8=np.array([[1,2,3],[4,5,6]])
arr9=np.array([1,2,3])
print(arr8+arr9) #arr9 is broadcast across the rows of arr8, adding [1, 2, 3] to each row.

[ 7  9 11 13 15]


# Hands-on: Applying Broadcasting to Real-World Scenarios

In [14]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
