# Indexing

In [1]:
import numpy as np

In [2]:
arr1 = np.array([10, 20, 30, 40])
print(arr1[0]) # first element
print(arr1[-1]) # last element

10
40


# Slicing(Extracting Parts of an Array) 

In [4]:
arr2 = np.array([10, 20, 30, 40, 50])
print(arr2[1:4]) # elements from index 1 to 3
print(arr2[:3]) # elements from index 0 to 2 or first three elements
print(arr2[::2]) # every 2nd element

# Slicing returns a view, not a copy! Changes affect the original array.
arr3 = np.array([1, 2, 3, 4])
arr4 = arr3[1:3]  # This is a view, not a copy
arr4[0] = -99  # Modify the slice

print(arr3) # Changing arr4 also changes arr3[1] because both refer to the same data in memory
print(arr4)

[20 30 40]
[10 20 30]
[10 30 50]
[  1 -99   3   4]
[-99   3]


# Fancy Indexing & Boolean Masking

In [6]:
# Fancy Indexing(Select Multiple Elements)
arr5 = np.array([10, 20, 30, 40, 50])
print(arr5[[0, 2, 4]]) # indices to be printed

# Boolean Masking
arr6 = np.array([1, 2, 3, 4, 5, 6])
print(arr6 > 3) # true for all values which is greater than 3
print(arr6[arr6 > 3]) # element which is greater than 3

[10 30 50]
[False False False  True  True  True]
[4 5 6]


# Exercises for Practice

In [6]:
# Question-1 : Create a 3×3 array filled with random numbers and print its shape.
random_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(random_arr.shape)

# Question-2 : Convert an array of floats [1.1, 2.2, 3.3] into integers.
float_arr = np.array([1.1, 2.2, 3.3])
print(float_arr.astype(np.int32))

# Question-3 : Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
even_num = np.array([1, 2, 3, 4, 5, 6])
print(even_num[[1, 3, 5]])

# Question-4 : Reshape a 1D array of size 9 into a 3×3 matrix.
arr = np.arange(1,10)
reshaped_arr = arr.reshape((3,3))
print(reshaped_arr)

# Question_5 : Use boolean masking to filter numbers greater than 50 in an array.
num = np.arange(20,60)
masked_arr = num > 50
print(num[masked_arr])

(3, 3)
[1 2 3]
[2 4 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[51 52 53 54 55 56 57 58 59]
