#Concept of Axis in Numpy

In [2]:
import numpy as np
arr1=np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(np.sum(arr1,axis=0)) # Sum along rows (down each column)
print(np.sum(arr1,axis=1)) # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


#Indexing in Multidimensional Arrays

In [6]:
#Accessing an element
print(arr1[1,2]) # Row index 1, Column index 2 → Output: 6
print(arr1[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

6
[[2 3]
 [5 6]]


#Indexing in 3D Arrays

In [6]:
#For 3D arrays, the first index refers to the "depth" (sheets of data).
arr2 = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
print(arr2)
print(arr2.shape)

# Accessing elements in 3D:

# First sheet, second row, third column
print(arr2[0, 1, 2])  # Output: 6
print(arr2[:, 0, :])   # Get the first row from both sheets

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
6
[[1 2 3]
 [7 8 9]]


In [9]:
# Selecting Data Along Axes

# Get all rows of the first column
first_col = arr1[:, 0]
print(first_col)  # Output: [1 4 7]

# Get the first row from each "sheet" in a 3D array
first_rows = arr2[:, 0, :]
print(first_rows)

[1 4 7]
[[1 2 3]
 [7 8 9]]


In [13]:
# Changing Data Along an Axis

# Replace all elements in column 1 with 0
arr2[:, 1] = 0
print(arr2)

[[[1 2 3]
  [0 0 0]]

 [[7 8 9]
  [0 0 0]]]
