In [4]:
# 1. Import the numpy package under the name np
import numpy as np

In [ ]:
# 2. Print the numpy version and the configuration
print("Numpy Version:",np.__version__)
np.show_config()

In [5]:
# 3. Create a null vector of size 10
arr1=np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
# 4. How to find the memory size of any array
arr2=np.array([1,2,3,4,5])
# print(arr2.nbytes)
print(arr2.size*arr2.itemsize)

20


In [17]:
# 5. How to get the documentation of the numpy add function from the command line?
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [19]:
# 6. Create a null vector of size 10 but the fifth value which is 1 (
arr3=np.zeros(10)
arr3[4]=1
print(arr3)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [25]:
# 7. Create a vector with values ranging from 10 to 49
arr4=np.arange(10,50)
print(arr4)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 8. Reverse a vector (first element becomes last) 
arr5=np.array([1,2,3,4,5])
# print(arr5[::-1])
print(np.flip(arr5))

In [39]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 
arr6=np.arange(0,9).reshape((3,3))
print(arr6)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
arr7=np.array([1,2,0,0,4,0])
print(np.nonzero(arr7)[0])

[0 1 4]


In [12]:
# 11. Create a 3x3 identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#12. Create a 3x3x3 array with random values
arr8=np.random.rand(3,3,3)
print(arr8)

[[[0.15177834 0.44187538 0.51292948]
  [0.48057689 0.7373723  0.70479688]
  [0.60328133 0.07252712 0.9329022 ]]

 [[0.40431009 0.64892144 0.94620228]
  [0.39242096 0.93966039 0.72774357]
  [0.4337327  0.827321   0.31088638]]

 [[0.85577951 0.6750453  0.91241636]
  [0.43551173 0.12962513 0.58292389]
  [0.24805804 0.12802745 0.15062676]]]


In [13]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values
arr9=np.random.rand(10,10)
print(arr9.max())
print(arr9.min())

0.9954487447913889
0.004260338520327256


In [21]:
# 14. Create a random vector of size 30 and find the mean value
arr10=np.random.rand(30)
print(arr10.mean())

0.5917338067219273


In [27]:
# 15. Create a 2d array with 1 on the border and 0 inside
arr11=np.array([[1,1,1],[1,0,1],[1,1,1]])
print(arr11)

n=3
arr12=np.ones((n,n)) #2nd method 
arr12[1:-1,1:-1]=0
print(arr12)

[[1 1 1]
 [1 0 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [10]:
# 16. How to add a border (filled with 0's) around an existing array?
arr13=np.arange(3,3)
arr13[1:-1,1:-1]=0
print(arr13)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed